// <auto-generated />
namespace Organizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_user_user_observations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_user_user_observations));
        
        string IMigrationMetadata.Id
        {
            get { return "201811171055422_added_user_user_observations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
